### ISSUE TITLE
Import Myriatrix dataset

### ISSUE THREAD

**Issue by dimus** [GlobalNamesArchitecture/dwca_hunter#26] opened 2020-05-25 22:34 UTC
@Archilegt wrote:

The data is downloadable in DwC. See the copy in GBIF for reference: http://www.gbif-uat.org/dataset/61e2d02a-34f7-4705-8840-c1ee49dfd951

@Archilegt, do you know if all your names get ingested into GBIF taxonomic backbone? If yes, I do get them already through GBIF darwin core file

**Comment by dimus** [comment] 2020-05-31 01:36
@Archilegt I imported your DwCA file, however it does seem to provide any description of the dataset in the elm metadata. If you give me a not-too-long description/citation I'll include it into the file and it will show up.

http://resolver.globalnames.org/data_sources/193

**Comment by Archilegt** [comment] 2020-06-03 09:10
For some reason the "Dataset description" is not sent from Scratchpads to GBIF. The issue is documented [here](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6144) and may have been solved [here](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6202). It awaits for the next release, which may happen in a few days.
I wrote a short dataset description that didn't make it to GBIF because of the mentioned issue. It is:
"Myriatrix -The Fellegship of the Rings | A Scratchpads-based classification for Myriapoda and Onychophora."

**Comment by dimus** [comment] 2020-06-08 17:58
Thanks @Archilegt, added description by hand for now.

**Comment by dimus** [comment] 2021-01-26 03:46
Update Myriatrix 2021-01-25

**Comment by dimus** [comment] 2021-01-26 03:48
@Archilegt I want to update your  Myriatrix data, but looks like URL you gave me last time is gone now. Can you give an updated URL?

**Comment by Archilegt** [comment] 2021-02-12 08:31
Issue [DWCA files can't be ingested by GBIF #6144](https://github.com/NaturalHistoryMuseum/scratchpads2/issues/6144) fixed via issue [Ben/gbif registry #6327](https://github.com/NaturalHistoryMuseum/scratchpads2/pull/6327).

**Comment by dimus** [comment] 2021-02-22 12:37
imported Myriatrix from http://myriatrix.myspecies.info/gbif-dwca.zip

**Closed** 2023-03-06 12:44 UTC
